Update azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -170,8 +170,16 @@ jobs:
 
             foreach ($projectFile in $projectFiles)
             {
-              echo "Pack command: dotnet " + (($arguments + $projectFile) -join ' ')
-              & dotnet ($arguments + $projectFile)
+              try
+              {
+                echo "Pack command: dotnet " + (($arguments + $projectFile) -join ' ')
+                & dotnet ($arguments + $projectFile)
+              }
+              catch
+              {
+                echo 'Failed to pack $(projectFile)'
+                exit 1
+              }
             }
 
             $pushToAzureArtifacts = $pack
